version: "3.8"
services:
  test-db:
    image: mysql:5.6
    environment:
      MYSQL_PASSWORD: password
      MYSQL_USER: user
      MYSQL_DATABASE: kita
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    command: --sql-mode="STRICT_ALL_TABLES"
  runner:
    image: node:12
    user: ${CURRENT_UID}
    working_dir: /home/node
    volumes:
      - ./:/home/node
    depends_on:
      - test-db