version: 2.1
orbs:
  node: circleci/node@4.0.0
jobs:
  test:
    docker:
      - image: 'cimg/node:lts'
      - image: mysql:5.6
        name: test-db
        environment:
          MYSQL_PASSWORD: password
          MYSQL_USER: user
          MYSQL_DATABASE: kita
          MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test:container
          name: Test
  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run lint
          name: Lint

workflows:
  default:
    jobs:
      - test
      - lint